server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/identity_service
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signKey: "CdqlCj2kUqoVhu5/rvWMmi6jFxtoC25m7Zlr+o6dGYWveD2g/H+nEc2FLzKlolu0"
